SEO 4: Blog detail page
prixite/prixite.github.io pull request #344
Opened 2023-04-14 12:20 UTC by imrancs058

- [ ]  Title (<title>) of the blog detail page should be blog title.
- [ ]  Facebook button on the header section of the blog should share the blog on Facebook.
- [ ]  LinkedIn button on the header section of the blog should share the blog on LinkedIn.
- [ ]  When we share the link of the blog, it should show a preview of the main image and text.

2023-04-15 17:37 UTC, umairwaheed commented on pages/blog/[slug].tsx
> +                  'https://e963-39-40-250-233.ngrok-free.app/blog/annual-lunch-2023'
Can you remove this hard-coded value?

2023-04-15 17:39 UTC, umairwaheed commented on pages/blog/[slug].tsx
> +                  'https://e963-39-40-250-233.ngrok-free.app/blog/annual-lunch-2023'
```suggestion
`${process.env.NEXT_PUBLIC_BASEPATH}/${router.asPath}`
```

2023-04-15 17:39 UTC, umairwaheed requested changes
Remove hard-coded path.

2023-04-17 05:00 UTC, imrancs058 commented on pages/blog/[slug].tsx
> +                  'https://e963-39-40-250-233.ngrok-free.app/blog/annual-lunch-2023'
Done as suggested

2023-04-17 05:00 UTC, imrancs058 commented
> Remove hard-coded path.

Done as Suggested

2023-04-17 12:54 UTC, umairwaheed approved these changes

2023-04-17 12:55 UTC, merged