Added Client Page
prixite/prixite.github.io pull request #44
Opened 2022-06-14 07:30 UTC by uzairmirza90

Conflicts resolved with upstream master.

2022-06-15 15:04 UTC, getalihassan approved these changes

2022-06-15 15:09 UTC, getalihassan commented
@umairwaheed @uzairmirza90 reviewed

2022-06-16 11:06 UTC, getalihassan commented
@uzairmirza90 please resovlve conflicts

2022-06-16 12:48 UTC, uzairmirza90 commented
@getalihassan   Resolved.

2022-06-16 13:04 UTC, getalihassan requested changes

2022-06-16 13:04 UTC, getalihassan commented on components/ClientCard/ClientCard.tsx
> +          alignItems: 'center',
can we refactor this and do styling in MUI style?

2022-06-16 13:05 UTC, getalihassan requested changes

2022-06-16 13:05 UTC, getalihassan commented on components/ClientCard/ClientCard.tsx
> +            flexDirection: 'column',
can we refactor this and do styling in MUI style?

2022-06-16 13:05 UTC, getalihassan commented on styles/pagesStyles/clients.scss
> +.clients-page {
try not to use scss, use useStyle hook

2022-06-20 12:32 UTC, uzairmirza90 commented
@getalihassan  Removed in-line styles into added into separate Scss file and conflicts are resolved.

2022-06-20 18:30 UTC, getalihassan approved these changes

2022-06-21 04:37 UTC, umairwaheed commented
@uzairmirza90 can you make the CI pass?

2022-06-21 04:39 UTC, umairwaheed requested changes
CI is not passing.

2022-06-22 05:07 UTC, umairwaheed requested changes
@uzairmirza90 yarn.lock should be tracked. Don't delete it please. Can you also resolve conflicts?

2022-06-22 10:17 UTC, umairwaheed requested changes
There are conflicts.

2022-06-23 05:43 UTC, umairwaheed commented
@uzairmirza90 can resolve the conflicts?

2022-06-23 08:54 UTC, merged