Jobs page added.
prixite/prixite.github.io pull request #45
Opened 2022-06-14 12:12 UTC by uzairmirza90

2022-06-15 15:03 UTC, getalihassan commented
@uzairmirza90 resolve conflicts

2022-06-16 09:44 UTC, uzairmirza90 commented
> @uzairmirza90 resolve conflicts

Conflicts resolved.

2022-06-16 11:07 UTC, getalihassan commented
@uzairmirza90 can you resolve conflicts again on this? :')

2022-06-16 12:58 UTC, uzairmirza90 commented
@getalihassan  Please merge https://github.com/prixite/prixite.github.io/pull/44 PR first, otherwise it will show conflicts again

2022-06-16 13:10 UTC, getalihassan requested changes

2022-06-16 13:10 UTC, getalihassan commented on components/JobCard/JobCard.tsx
> +        direction={{ xs: 'column', md: 'row' }}
avoid inline styling and try to use MUI styling hook

2022-06-16 13:10 UTC, getalihassan commented on components/JobCard/JobCard.tsx
> +          boxShadow: 'rgba(0, 0, 0, 0.24) 0px 3px 8px',
avoid inline styling and try to use MUI styling hook

2022-06-16 13:10 UTC, getalihassan commented on components/JobCard/JobCard.tsx
> +          <Box sx={{ display: 'flex', justifyContent: 'space-between' }}>
avoid inline styling and try to use MUI styling hook

2022-06-16 13:10 UTC, getalihassan commented on components/JobCard/JobCard.tsx
> +            <Typography fontSize={18} variant="h6">
avoid inline styling and try to use MUI styling hook

2022-06-16 13:10 UTC, getalihassan commented on styles/pagesStyles/jobs.scss
> +.jobs-page {
try to avoid scss if necessary

2022-06-20 18:30 UTC, getalihassan approved these changes

2022-06-21 04:37 UTC, umairwaheed commented
@uzairmirza90 can make the CI pass?

2022-06-21 04:39 UTC, umairwaheed requested changes
CI is not passing.

2022-06-21 11:08 UTC, uzairmirza90 commented
@umairwaheed  CI passed

2022-06-22 05:04 UTC, umairwaheed requested changes
@uzairmirza90 we don't include virtual environment in Git. Please remove venv folder.

2022-06-22 08:59 UTC, umairwaheed requested changes
@uzairmirza90 please do not delete yarn.lock file.

2022-06-22 10:10 UTC, uzairmirza90 commented
@umairwaheed  yarn.lock file added

2022-06-22 10:16 UTC, umairwaheed approved these changes
LGTM

2022-06-22 10:16 UTC, merged